### PR TITLE
Add repeats to string parsing, fix string error checking

### LINKED ISSUE #48: Support for parsing the specified repeats in stringToPulseTrain
I know ESPiLight in `stringToPulseTrain` means to implement the pulse train string format seen [here](https://github.com/pilight/pilight-usb-nano/blob/master/pilight_usb_nano.c):

`c:102020202020202020220202020020202200202200202020202020220020202203;p:279,2511,1395,9486;r:5@`

but it looks like the repeats part (e.g. `r:10`) is not implemented. Repeats are supported in `sendPulseTrain` as an argument. When sending raw pulses, one would usually input the string (including the repeats) to `stringToPulseTrain`, and then feed the resulting codes and length into `sendPulseTrain`. It would complete the circle if `stringToPulseTrain` could also report the number of repeats specified.

I'm working on a PR to do this.

### PR DESCRIPTION
**Pull request by melyux**
This adds support for specifying repeats in the pulse train string input to `stringToPulseTrain`, as supported by Pilight (e.g. `r:12`) [here](https://github.com/pilight/pilight/blob/staging/libs/pilight/hardware/433nano.lua) and [here](https://github.com/pilight/pilight-usb-nano/blob/master/pilight_usb_nano.c). This resolves #48.

It also fixes an existing bug with verifying the string for the `c:` and `p:` components which always produced false negatives.

I'm not sure about the argument passing and returning implementation I've used here, so I'm open to suggestions on how to do it better. So I've held off on modifying the following test and example that use it:

https://github.com/puuu/ESPiLight/blob/969ab14113f19859e43ce7bc4db69104b30833db/tests/test_parse/test_parse.ino#L75

https://github.com/puuu/ESPiLight/blob/969ab14113f19859e43ce7bc4db69104b30833db/examples/Transmit_Raw/Transmit_Raw.ino#L20-L23

### CODE REVIEW

**Comment by puuu** [comment]
@melyux thank you for contributing!

The bug in verifying the string for the `c:` and `p:` is a good catch. I would prefer this as a separate commit (even better as a separate pull request).

About #48, I definitively welcome this feature!

But I don't like the proposal with a pointer as a function parameter. In this library I've avoided pointer parameters (unless they're an array) entirely. Furthermore, this change breaks the API, as you pointed out by changing the tests and examples.

I am open to other suggestions. Right now I don't have a good idea how to implement this in a clean way. How about a separate function `int ESPiLight::stringToRepeats(const String &data, size_t maxlength)` that only parse for the repeats?

File: src/ESPiLight.h [hunk 1]
```diff
@@ -167,8 +167,9 @@ class ESPiLight {
    */
   static const int ERROR_INVALID_PULSETRAIN_MSG_C = -1;
   static const int ERROR_INVALID_PULSETRAIN_MSG_P = -2;
-  static const int ERROR_INVALID_PULSETRAIN_MSG_END = -3;
-  static const int ERROR_INVALID_PULSETRAIN_MSG_TYPE = -4;
+  static const int ERROR_INVALID_PULSETRAIN_MSG_R = -3;
+  static const int ERROR_INVALID_PULSETRAIN_MSG_END = -4;
```
Comment (puuu) [inline src/ESPiLight.h:171]: Please do not change existing constants, just add a new one.

Comment (melyux) [reply src/ESPiLight.h:171]: Thought it was better to put it in this order in this case because MSG_R is more similar to MSG_C and MSG_P than the other two. But yeah can move it to the end instead

**Comment by melyux** [comment]
Sorry about the delay. That sounds like a good solution to the problem. Another one could be returning a struct, with one element being the int length and the other being the int repeats.

**Comment by melyux** [comment]
Split the change into two PRs.

**Comment by puuu** [comment]
Sorry for my late reply.

Probably my mistake, the `maxlength` parameter is not needed, can you remove it?

If possible, also add a test into `tests/test_parse/test_parse.ino`.

**Comment by melyux** [comment]
Removed the `maxLength` parameter. Must have slipped my mind. Working on the test.

**Comment by melyux** [comment]
Added the test to the file mentioned.

**Comment by melyux** [comment]
Fixed the line length to make Travis happy.

**Comment by puuu** [comment]
Thanks, perfect.
